// <auto-generated />
using System;
using HeyYou.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HeyYou.Migrations
{
    [DbContext(typeof(HeyYouContext))]
    [Migration("20210120183513_SeedData")]
    partial class SeedData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("HeyYou.Models.Group", b =>
                {
                    b.Property<int>("GroupId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("GroupDescription");

                    b.Property<string>("GroupName");

                    b.HasKey("GroupId");

                    b.ToTable("Groups");

                    b.HasData(
                        new
                        {
                            GroupId = 1,
                            GroupDescription = "Best I can do is 600",
                            GroupName = "Pawn Stars"
                        },
                        new
                        {
                            GroupId = 2,
                            GroupDescription = "Life isn't all diamonds and rose, but it should be.",
                            GroupName = "Real Housewives"
                        });
                });

            modelBuilder.Entity("HeyYou.Models.GroupMessage", b =>
                {
                    b.Property<int>("GroupMessageId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("GroupId");

                    b.Property<int>("MessageId");

                    b.HasKey("GroupMessageId");

                    b.HasIndex("GroupId");

                    b.HasIndex("MessageId");

                    b.ToTable("GroupMessage");
                });

            modelBuilder.Entity("HeyYou.Models.Message", b =>
                {
                    b.Property<int>("MessageId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("MessageAuthor");

                    b.Property<string>("MessageBody");

                    b.Property<DateTime>("MessageDate");

                    b.Property<string>("MessageTitle");

                    b.HasKey("MessageId");

                    b.ToTable("Messages");

                    b.HasData(
                        new
                        {
                            MessageId = 1,
                            MessageAuthor = "Chuck Palahniuk",
                            MessageBody = "The first rule of fight club is you don't talk about fight club",
                            MessageDate = new DateTime(2020, 5, 1, 8, 30, 53, 0, DateTimeKind.Unspecified),
                            MessageTitle = "Fight Club"
                        },
                        new
                        {
                            MessageId = 2,
                            MessageAuthor = "William S Burroughs",
                            MessageBody = "Drugs",
                            MessageDate = new DateTime(2020, 5, 1, 8, 30, 53, 0, DateTimeKind.Unspecified),
                            MessageTitle = "Naked Lunch"
                        },
                        new
                        {
                            MessageId = 3,
                            MessageAuthor = "Janet Fitch",
                            MessageBody = "prisons and mommy issues",
                            MessageDate = new DateTime(2020, 5, 1, 8, 30, 53, 0, DateTimeKind.Unspecified),
                            MessageTitle = "White Oleander"
                        },
                        new
                        {
                            MessageId = 4,
                            MessageAuthor = "Hemingway",
                            MessageBody = "seas",
                            MessageDate = new DateTime(2020, 5, 1, 8, 30, 53, 0, DateTimeKind.Unspecified),
                            MessageTitle = "oldmen"
                        },
                        new
                        {
                            MessageId = 5,
                            MessageAuthor = "H.P. Lovecraft",
                            MessageBody = "lets get weird",
                            MessageDate = new DateTime(2020, 5, 1, 8, 30, 53, 0, DateTimeKind.Unspecified),
                            MessageTitle = "lets get dark"
                        });
                });

            modelBuilder.Entity("HeyYou.Models.GroupMessage", b =>
                {
                    b.HasOne("HeyYou.Models.Group", "Group")
                        .WithMany("JoinEntries")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("HeyYou.Models.Message", "Message")
                        .WithMany("JoinEntries")
                        .HasForeignKey("MessageId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
